In [4]:
import numpy as np
import pandas as pd

In [5]:
movies = pd.read_csv("../data/movie_metadata.csv")
movies.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                 40000.0  309404152.0         Action|Adventure|Fantasy   
2                 11000.0  200074175.0        Action|Adventure|Thriller   
3                 27000.0  448130642.0                  Action|Thriller   
4                   131.0          NaN                      Documentary   

          ...          num_user_for_reviews language  country  content_rating  \
0         ...                        3054.0  English      USA           PG-13   
1         ...                        1238.0  English      USA           PG-13   
2         ...                         994.0  English       UK           PG-13   
3         ...                        2701.0  English      USA           PG-13   
4         ...                           NaN      NaN      NaN             NaN   

        budget  title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0  237000000.0      2009.0                  936.0        7.9          1.78   
1  300000000.0      2007.0                 5000.0        7.1          2.35   
2  245000000.0      2015.0                  393.0        6.8          2.35   
3  250000000.0      2012.0                23000.0        8.5          2.35   
4          NaN         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [5]:
np.random.seed(8055)

In [244]:
data1 = [163, 12, 23, 311, 44, 75, 82, 122, 219, 247, 5, 251, 118]
# spiderman, batvssuper, amazing spiderman, bat forever, green lantern, suicide squad, iron man 2, batman 1, bat and robin
# tmnt, dark knight, fantastic four, hancock

In [246]:
tx = data1
ty = data1[1:]
ty.append(data1[0])
tx, ty

([163, 12, 23, 311, 44, 75, 82, 122, 219, 247, 5, 251, 118],
 [12, 23, 311, 44, 75, 82, 122, 219, 247, 5, 251, 118, 163])

In [247]:
df = pd.DataFrame(columns=['a', 'b'])
df['a'] = tx
df['b'] = ty
df

a    b
0   163   12
1    12   23
2    23  311
3   311   44
4    44   75
5    75   82
6    82  122
7   122  219
8   219  247
9   247    5
10    5  251
11  251  118
12  118  163

In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
scalar = MinMaxScaler((-1, 1))

In [19]:
scalar.fit(df.values)

/home/nischal/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(-1, 1))

In [20]:
scaled_X = scalar.transform(df.values)

In [21]:
scaled_X

array([[ 0.03267974, -0.92282958],
       [-0.95424837, -0.85209003],
       [-0.88235294,  1.        ],
       [ 1.        , -0.7170418 ],
       [-0.74509804, -0.51768489],
       [-0.54248366, -0.47266881],
       [-0.49673203, -0.21543408],
       [-0.23529412,  0.40836013],
       [ 0.39869281,  0.58842444],
       [ 0.58169935, -0.96784566],
       [-1.        ,  0.61414791],
       [ 0.60784314, -0.24115756],
       [-0.26143791, -1.        ]])

In [24]:
X, y = scaled_X[:, 0:-1], scaled_X[:, -1]
X, y

(array([[ 0.03267974],
        [-0.95424837],
        [-0.88235294],
        [ 1.        ],
        [-0.74509804],
        [-0.54248366],
        [-0.49673203],
        [-0.23529412],
        [ 0.39869281],
        [ 0.58169935],
        [-1.        ],
        [ 0.60784314],
        [-0.26143791]]),
 array([-0.92282958, -0.85209003,  1.        , -0.7170418 , -0.51768489,
        -0.47266881, -0.21543408,  0.40836013,  0.58842444, -0.96784566,
         0.61414791, -0.24115756, -1.        ]))

In [26]:
X = X.reshape(X.shape[0], 1, X.shape[1])

array([[[ 0.03267974]],

       [[-0.95424837]],

       [[-0.88235294]],

       [[ 1.        ]],

       [[-0.74509804]],

       [[-0.54248366]],

       [[-0.49673203]],

       [[-0.23529412]],

       [[ 0.39869281]],

       [[ 0.58169935]],

       [[-1.        ]],

       [[ 0.60784314]],

       [[-0.26143791]]])

In [35]:
X.shape

(13, 1, 1)

In [107]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, GRU

In [110]:
model = Sequential()

In [109]:
GRU?

In [111]:
model.add(GRU(50, batch_input_shape=(1, X.shape[1], X.shape[2]), return_sequences=True))

In [112]:
model.add(GRU(100, return_sequences=True))

In [113]:
model.add(GRU(300))

In [114]:
model.add(Dense(1))

In [115]:
model.compile(loss='mse', optimizer='adam')

In [116]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru_1 (GRU)                  (1, 1, 50)                7800      
_________________________________________________________________
gru_2 (GRU)                  (1, 1, 100)               45300     
_________________________________________________________________
gru_3 (GRU)                  (1, 300)                  360900    
_________________________________________________________________
dense_10 (Dense)             (1, 1)                    301       
Total params: 414,301.0
Trainable params: 414,301
Non-trainable params: 0.0
_________________________________________________________________


In [117]:
for i in range(5):
    print("Cycle: {}".format(i + 1))
    h = model.fit(X, y, epochs=100, batch_size=1, verbose=0)
    model.reset_states()

Cycle: 1
Cycle: 2
Cycle: 3
Cycle: 4
Cycle: 5


In [118]:
np.mean(h.history['loss'])

0.3965089888703453

In [137]:
alp = 75
t=[alp, alp]

In [138]:
tt = np.reshape(t, (1, 2))
tt = scalar.transform(tt)

In [139]:
ttt = np.reshape(tt[0][0], (1, 1, 1))

In [141]:
p = model.predict(ttt)
p

array([[-0.24989016]], dtype=float32)

In [144]:
scalar.inverse_transform([p[0][0], p[0][0]])

/home/nischal/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([ 119.76680498,  116.64207957])

In [248]:
df

a    b
0   163   12
1    12   23
2    23  311
3   311   44
4    44   75
5    75   82
6    82  122
7   122  219
8   219  247
9   247    5
10    5  251
11  251  118
12  118  163

In [249]:
vals = df.values

In [250]:
X, y = vals[:, 0:-1], vals[:, -1]
X, y

(array([[163],
        [ 12],
        [ 23],
        [311],
        [ 44],
        [ 75],
        [ 82],
        [122],
        [219],
        [247],
        [  5],
        [251],
        [118]]),
 array([ 12,  23, 311,  44,  75,  82, 122, 219, 247,   5, 251, 118, 163]))

In [251]:
X = X.reshape(X.shape[0], 1, X.shape[1])

In [262]:
del model2
model2 = Sequential()
model2.add(GRU(50, batch_input_shape=(1, X.shape[1], X.shape[2]), 
               stateful=True, return_sequences=True))
model2.add(GRU(100, stateful=True, return_sequences=True))
model2.add(GRU(300, stateful=True))
model2.add(Dense(1))
model2.compile(loss='mse', optimizer='rmsprop')
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru_27 (GRU)                 (1, 1, 50)                7800      
_________________________________________________________________
gru_28 (GRU)                 (1, 1, 100)               45300     
_________________________________________________________________
gru_29 (GRU)                 (1, 300)                  360900    
_________________________________________________________________
dense_32 (Dense)             (1, 1)                    301       
Total params: 414,301.0
Trainable params: 414,301
Non-trainable params: 0.0
_________________________________________________________________


In [263]:
del h
for i in range(2500):
    h = model2.fit(X, y, epochs=1, batch_size=1, verbose=0, shuffle=False)
    model2.reset_states()
    if i % 100 == 0:
        print("Cycle: {}, loss: {}".format(i, h.history['loss'][-1]))

Cycle: 0, loss: 21458.40326984112
Cycle: 100, loss: 5635.401522416335
Cycle: 200, loss: 4583.475242321308
Cycle: 300, loss: 3385.8016372838847
Cycle: 400, loss: 3299.428694206935
Cycle: 500, loss: 89.26840479559122
Cycle: 600, loss: 2.931616234736374
Cycle: 700, loss: 1.3216249035814633
Cycle: 800, loss: 3.654921636670434
Cycle: 900, loss: 0.49138081517930216
Cycle: 1000, loss: 0.9833740925129789
Cycle: 1100, loss: 0.36784908376061
Cycle: 1200, loss: 1.6573737884441821
Cycle: 1300, loss: 0.8279303507879376
Cycle: 1400, loss: 0.26076871873094487
Cycle: 1500, loss: 0.2504925028098604
Cycle: 1600, loss: 0.09386995400731954
Cycle: 1700, loss: 0.1502519706488014
Cycle: 1800, loss: 0.19241912605670783
Cycle: 1900, loss: 0.2119744851325567
Cycle: 2000, loss: 0.126487371010276
Cycle: 2100, loss: 0.16153147347414723
Cycle: 2200, loss: 0.004316448356033876
Cycle: 2300, loss: 0.15834135723371917
Cycle: 2400, loss: 0.13153432297706155


In [272]:
ap = 44
model2.predict(np.reshape(ap, (1, 1, 1)))

array([[ 13.88193035]], dtype=float32)

In [204]:
df

a    b
0   163   12
1    12   23
2    23  311
3   311   44
4    44   75
5    75   82
6    82  122
7   122  219
8   219  247
9   247    5
10    5  251
11  251  118
12  118  163
13  163    0